language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -qq install cmake
  - sudo apt-get install libgtest-dev
  - pushd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - sudo apt-get install google-mock
  - popd

script:
    make

branches:
  only:
    - master

notifications:
  recipients:
    - sebastian@madajczyk.net
  email:
    on_success: change
    on_failure: always
