language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -qq install cmake
  - sudo apt-get install libgtest-dev
  - sudo apt-get install google-mock

script:
    make

branches:
  only:
    - master

notifications:
  recipients:
    - sebastian@madajczyk.net
  email:
    on_success: change
    on_failure: always
